### PR TITLE
Handle document review of #107

### PR DESCRIPTION
**Pull request by ckormanyos**

### CODE REVIEW

**Comment by ckormanyos** [comment]
Hi @S-Streulicht could you please check the [update docs](https://github.com/ckormanyos/mandelbrot/tree/review_docs107?tab=readme-ov-file#deep-dives-and-acceleration-via-perturbation) based on your review points from #107?

**Comment by ckormanyos** [comment]
Handled by #110

**Review by S-Streulicht — CHANGES_REQUESTED** [review]
Looks mostly ok but line 357:
The formularndoesent contail a z_k it is just
Z_k+1 + e_k+1 = z_k^2 + c +e_k^2 + 2*z_k*e_k + d
inprinciple the original formular + then e formula you give later on no additional terms.

**Comment by ckormanyos** [comment]
> The formularndoesent contain a $z_{k}$

OK. Thanks @S-Streulicht. That makes sense. I got it. I'll correct that.

**Pull request merged**
