### PR TITLE
Add png support

### PR DESCRIPTION
**Pull request by S-Streulicht**
Functional changes: output two pictures one png and one jpeg.
details for the two new libs can be found in the readme.md
to do code opion to choose between png and jpeg
output raw data as png to be able to color stretch it externally.

### CODE REVIEW

**Comment by ckormanyos** [comment]
Hi @S-Streulicht this is a great evolution. For quite some time, I have wanted to store raw data for future color stretching and histogram-methods.

Please give me a day or so to look at this stuff.

Do you feel this PR is ready to merge?

**Comment by ckormanyos** [comment]
You did a great job, @S-Streulicht, building zlib on the fly. Good work. That looks nice.

Is there anything in particular I should look at? Otherwise, I'm good to go on this PR... Nice job!

**Comment by ckormanyos** [comment]
This is intended to address #129

**Comment by S-Streulicht** [comment]
I'm fine with the PR.

The big thing is done (png cleaned and working zlib working) but there are a lot of small things to be done:
- sonar not working, I forgot to provide include path lib name and path. And I'm still unable to runn it in general.
- I have to admid that I did only compile and test the code with visual studio, locally. I did not compare the resulting png pictures from the ubuntu / macOS Tests.
- The buildsystem in the test is not optimal:
-- there is a pnglibconfig file, which "just" has to be copied and renamed. I do this outside the makefile, Because of an lack of understanding how it is done inside.
-- Strangly the gcc-native test don't need to have the pnglibconfig.h files copied, I did not figure where config information are comming from, in that systems.
-- I use only one makefile for all systems, which means to get the ARM cpu from the macOS running all tests have arm specific code. the png lib itself is guarding it so it is not an issue, but why should be 3 files (in arm folder) compiled which are not needed?
- the biggest annoying thing is the zlib. I did not fix the compilation warnings, because it is way more complex than the png lib. There are some functions which need to have different types. Here I see some danger to brake the system because I don't see all the effects a change has. Also the names of the typs seems to be less speeking.

- Future plan:
-- I showed only that it is possible to write an png, but neither I included a backend to choose either jpeg or png
-- directly write the plain (none coler stretched) data.
-- also I want to copie the config files as meter information in the png.
-- I wander if a small (flexible) program for color stretching is needed. I think not because standard program like gimp might do the trick.

**Comment by ckormanyos** [comment]
Hi @S-Streulicht thank you for the complete details above. Let's merge this now. Most or basically all the points you mention above I can handle.

I'd leave the third party libraries alone and preferably switch off compilation warnings. In hindsight, I'm not entirely sure that getting JPEG warning-free was even worth the effort. Those are supported libraries so snychronizing them in their current state (as in left alone) will be easier in the future.

We will need to see if compile-time or run-time decision of the output form is better. It might be best to simply write both output forms by default.

I can clean up build systems and those kinds of details. leave that to me.

Merging.

Many thanks for this technological jump @S-Streulicht !

**Pull request merged**
