### PR TITLE
Update readme file

### PR DESCRIPTION
**Pull request by imahjoub**

### CODE REVIEW

**Comment by ckormanyos** [comment]
Hi @imahjoub I just approved this CI run (needed as default setting in this repo for first time contributors). Thanks. Let's see how this plays out in CI and visually.

**Comment by imahjoub** [comment]
> I do expect troubles with owner/fork on SONAR

yes I used my own token, this is probably the wrong way to set up sonar in a forked repo.

**Comment by ckormanyos** [comment]
> used my own token, this is probably the wrong way to set up sonar in a forked repo

You will be able to perform Sonar analyses on PRs to your own fork, but not if your PR is intended for the main branch of my (this) repository. The problem is, you probably need to personalize the sonar properties in the root directory of the repository and these will differ from the properties that I need.

it's probably best if I set up sonar with my own credentials here and we find out (also mentioned in other repositories) how to allow sonar analyses for forked repositories and contributors, as I think this is possible, but I simply do not know how to do it.

**Comment by ckormanyos** [comment]
Hi @imahjoub as mentioned above, after merging this PR (a bit later when I've got time), I will need to register this repo at LGTM and sonar and ultimately need my own personalization of the sonar properties, as [your personalized sonar properties](https://github.com/imahjoub/mandelbrot/blob/c7e2f4c2458f72296f509c29436e7305826d421d/sonar-project.properties#L1) will not work (yet).

**Comment by ckormanyos** [comment]
Thank you for looking into this Iliass (@imahjoub)!

**Comment by ckormanyos** [comment]
Hi @imahjoub sorry I had overlooked this PR for a few weeks.
Finally merged!
Many thanks.

**Comment by imahjoub** [comment]
Hi @ckormanyos,
Actually, I wanted to take over the topic #10, but unfortunately I haven't got around to it yet.
I will do that soon...

**Comment by ckormanyos** [comment]
> also to take over the topic #10 

Great idea @imahjoub that will be cool. There is, however, no hurry for this. Sounds like a cool cold.-weather winter project...

**Comment by imahjoub** [comment]
> Sounds like a cool cold.-weather winter project...

yes exactly Haha

**Pull request merged**
